# Generated by Django 5.1.6 on 2025-02-11 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_sucursal_producto_sucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='sucursal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='app.sucursal'),
        ),
    ]
