# Generated by Django 5.1.6 on 2025-02-11 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_producto_sucursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='sucursal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='app.sucursal'),
        ),
    ]
