# Generated by Django 5.1.6 on 2025-02-11 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_producto_sucursal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='sucursal',
        ),
        migrations.DeleteModel(
            name='Sucursal',
        ),
    ]
